import Link from "next/link";
import { createInvitation, createOwner, removeOwner, resetOwnerPassword, signOut } from "@/app/actions";
import { currentUser } from "@/lib/auth";
import { prisma } from "@/lib/prisma";

export default async function AdminPage({ searchParams }: PageProps<"/admin">) {
  const user = await currentUser();
  if (!user) return <main className="auth-page"><section className="auth-card"><h1>招待状の管理画面</h1><p>ログインすると、招待状の作成と編集ができます。</p><Link className="button" href="/login">ログイン</Link></section></main>;
  const { error, notice } = await searchParams;
  const [invitations, owners] = await Promise.all([
    prisma.invitation.findMany({ where: user.isAdmin ? {} : { members: { some: { userId: user.id } } }, orderBy: { updatedAt: "desc" } }),
    user.isAdmin ? prisma.owner.findMany({ orderBy: { email: "asc" } }) : Promise.resolve([]),
  ]);
  const ownerEmails = new Map(owners.map((owner) => [owner.userId, owner.email]));
  return <main className="admin-page"><header><div><p className="eyebrow">INVITATION STUDIO</p><h1>{user.isAdmin ? "ユーザー管理画面" : "あなたの招待状"}</h1></div><form action={signOut}><button className="quiet">ログアウト</button></form></header>{error && <p className="error" role="alert">{error}</p>}{notice && <p className="notice">{notice}</p>}{user.isAdmin && <><section className="editor-card"><h2>オーナーを追加</h2><form action={createOwner} className="editor-form"><label>メールアドレス<input name="email" type="email" autoComplete="off" required /></label><label>初期パスワード<input name="password" type="password" minLength={8} autoComplete="new-password" required /></label><button>オーナーを追加</button></form></section><section className="editor-card"><h2>オーナー一覧</h2><div className="owner-list">{owners.map((owner) => <article key={owner.id}><strong>{owner.email}</strong><form action={resetOwnerPassword.bind(null, owner.id)} className="owner-actions"><input name="password" type="password" minLength={8} autoComplete="new-password" placeholder="新しいパスワード" required /><button className="secondary">パスワードを再設定</button></form><form action={removeOwner.bind(null, owner.id)}><button className="quiet">削除</button></form></article>)}{!owners.length && <p>オーナーはまだ登録されていません。</p>}</div></section></>}<section className="editor-card"><h2>{user.isAdmin ? "招待状一覧" : "あなたの招待状"}</h2><section className="invitation-list">{invitations.map((invite) => <Link href={`/admin/invite/${invite.slug}`} key={invite.id}><strong>{invite.groomName} & {invite.brideName}</strong><span>/invite/{invite.slug} · オーナー: {ownerEmails.get(invite.ownerId) ?? (user.isAdmin ? "削除済み" : user.email)} · {invite.isPublished ? "公開中" : "下書き"}</span></Link>)}{!invitations.length && <p>招待状はまだありません。</p>}</section></section>{user.isAdmin && <section className="editor-card"><h2>招待状を作成</h2><form action={createInvitation} className="editor-form"><label>新郎のお名前<input name="groomName" required maxLength={80} /></label><label>新婦のお名前<input name="brideName" required maxLength={80} /></label><label>オーナー<select name="ownerId" required defaultValue=""><option value="" disabled>オーナーを選択</option>{owners.map((owner) => <option value={owner.id} key={owner.id}>{owner.email}</option>)}</select></label><label>URLスラッグ<input name="slug" required pattern="[A-Za-z0-9-]+" placeholder="taro-and-hanako" /></label><label>日時<input name="eventAt" type="datetime-local" required /></label><label>会場<input name="venueName" required /></label><label>住所<input name="venueAddress" /></label><button disabled={!owners.length}>下書きを作成</button></form></section>}</main>;
}
