import Link from "next/link";
import { addScheduleItem, updateInvitation } from "@/app/actions";
import { editableInvitation } from "@/lib/invitations";

const localDate = (date: Date) => new Intl.DateTimeFormat("sv-SE", { timeZone: "Asia/Tokyo", dateStyle: "short", timeStyle: "short", hourCycle: "h23" }).format(date).replace(" ", "T");

export default async function InvitationEditor({ params, searchParams }: PageProps<"/admin/invite/[slug]">) {
  const { slug } = await params; const { notice, error } = await searchParams; const { invitation } = await editableInvitation(slug);
  const heroPaths = invitation.media.filter((media) => media.kind === "HERO").map((media) => media.storagePath).join("\n");
  return <main className="admin-page"><header><div><Link href="/admin" className="back-link">← 招待状一覧</Link><h1>{invitation.groomName} & {invitation.brideName} を編集</h1></div><Link className="button secondary" href={`/invite/${slug}`} target="_blank">プレビュー</Link></header>{notice && <p className="notice">{notice}</p>}{error && <p className="error">{error}</p>}<section className="editor-card"><form action={updateInvitation.bind(null, slug)} className="editor-form"><label>新郎のお名前<input name="groomName" defaultValue={invitation.groomName} required /></label><label>新婦のお名前<input name="brideName" defaultValue={invitation.brideName} required /></label><label>日時（日本時間）<input name="eventAt" type="datetime-local" defaultValue={localDate(invitation.eventAt)} required /></label><label>会場<input name="venueName" defaultValue={invitation.venueName} required /></label><label>住所<input name="venueAddress" defaultValue={invitation.venueAddress} /></label><label>Google Maps URL<input name="mapUrl" type="url" defaultValue={invitation.mapUrl ?? ""} /></label><label className="full">メッセージ<textarea name="message" rows={4} defaultValue={invitation.message} /></label><label className="full">ヒーロー画像をアップロード<input name="heroImages" type="file" accept="image/jpeg,image/png,image/webp,image/avif" multiple /></label><label className="full">ヒーロー画像のパス（任意・1行ずつ）<textarea name="heroPaths" rows={4} defaultValue={heroPaths} placeholder="taro-hanako/hero-1.webp" /></label><label className="check full"><input name="isPublished" type="checkbox" defaultChecked={invitation.isPublished} /> この招待状を公開する</label><button>変更を保存</button></form></section><section className="editor-card"><h2>スケジュール</h2><ol className="schedule-list">{invitation.schedule.map((item) => <li key={item.id}><time>{item.startsAt}</time><span><strong>{item.title}</strong>{item.detail && <small>{item.detail}</small>}</span></li>)}</ol><form action={addScheduleItem.bind(null, slug)} className="inline-form"><input name="startsAt" type="time" required /><input name="title" placeholder="項目名" required /><input name="detail" placeholder="詳細（任意）" /><button>追加</button></form></section></main>;
}
