import Link from "next/link";
import { addScheduleItem, updateInvitation } from "@/app/actions";
import { editableInvitation } from "@/lib/invitations";
import { isScheduleIcon, scheduleIcons } from "@/lib/schedule-icons";
import { InvitationEditor } from "./invitation-editor";

export default async function InvitationEditorPage({ params, searchParams }: PageProps<"/admin/invite/[slug]">) {
  const { slug } = await params; const { notice, error } = await searchParams; const { invitation } = await editableInvitation(slug);
  return <main className="admin-page"><header><div><Link href="/admin" className="back-link">← 招待状一覧</Link><h1>{invitation.groomName} & {invitation.brideName} を編集</h1></div><Link className="button secondary" href={`/invite/${slug}`} target="_blank">プレビュー</Link></header>{notice && <p className="notice">{notice}</p>}{error && <p className="error">{error}</p>}<section className="editor-card"><InvitationEditor action={updateInvitation.bind(null, slug)} invitation={{ ...invitation, eventAt: invitation.eventAt.toISOString() }} /></section><section className="editor-card"><h2>スケジュール</h2><ol className="schedule-list">{invitation.schedule.map((item, index) => { const icon = isScheduleIcon(item.icon ?? "") ? item.icon : scheduleIcons[index % scheduleIcons.length].value; return <li key={item.id}><time>{item.startsAt}</time><svg className="schedule-icon" viewBox="0 0 24 24" aria-hidden="true"><use href={`/icons/schedule/${icon}.svg#icon`} /></svg><span><strong>{item.title}</strong>{item.detail && <small>{item.detail}</small>}</span></li>; })}</ol><form action={addScheduleItem.bind(null, slug)} className="inline-form"><input name="startsAt" type="time" aria-label="開始時間" required /><input name="title" placeholder="項目名" aria-label="項目名" required /><label className="schedule-icon-field">アイコン<select name="icon" defaultValue="rings" required>{scheduleIcons.map((icon) => <option key={icon.value} value={icon.value}>{icon.label}</option>)}</select></label><input name="detail" placeholder="詳細（任意）" aria-label="詳細（任意）" /><button>追加</button></form></section></main>;
}
